### ISSUE TITLE
Improvements over ProtonUpdater?

### ISSUE THREAD

**Issue by imtbl** [patrickm32/proton-ge-custom-updater#4]
Until now, I’ve been using https://github.com/flubberding/ProtonUpdater (I also made an AUR package for it for convenience: https://aur.archlinux.org/packages/cproton-git).

From what I can see, there are currently not many differences between that script and yours, so I was wondering if you had anything special planned for the future (e.g., more extensive version management) that would make me want to use your version over ProtonUpdater?

From what I saw in a recent issue, the ProtonUpdater maintainer also wants to pick up development again soon and implement new features; maybe you could even collaborate together?

**Comment by p-mng** [comment]
Hi, I am open for a collaboration or maybe even merging the two projects if the maintainer of the script you mentioned should continue to actively work on his project. The goal of the script was not to be "better" than the cocurrency, it was more of a spare time project to improve my bash scripting skills. As far as I can tell, my script may have higher compatibility (e.g. with the flatpak version of Steam).

An improved version management system would be a great idea. One more thing I would like to implement is the ability to be able to compile the source code locally, which I probably won't get to in the next 2-3 weeks.

**Comment by p-mng** [comment]
I am watching the other repository from now on and contact the developer if he continues to work on the project. Therefore I will close the issue now, if there are any further questions just leave a comment.
