### ISSUE TITLE
Requires bash shell as default shell

### ISSUE THREAD

**Issue by Transistor4aCPU** [patrickm32/proton-ge-custom-updater#5]
The script is not compatible with fish shell as default.
Exchange  `#!/bin/sh` with `#!/bin/bash`

**Comment by p-mng** [comment]
Hi, the problem is that fish uses a different syntax to declare variables. I will try to add compatibility for that specific shell by detecting the `SHELL` environment variable tomorrow.

**Comment by Transistor4aCPU** [comment]
Most fish users will have bash installed in addition to fish, which is why it would be simpler to replace `#!/bin/sh` with `#!/bin/bash`

**Comment by p-mng** [comment]
Okay, I have updated the script for now. If there is no need for compatibility I will leave it like this, even though I think this is generally an issue with fish since the shell is not compatible with POSIX sh.
